package uk.gov.hmrc.agentclientrelationships.model.clientDetails

sealed trait ClientDetailsFailureResponse

case object ClientDetailsNotFound extends ClientDetailsFailureResponse
case object ClientDetailsDoNotMatch extends ClientDetailsFailureResponse
case class UnexpectedErrorRetrievingClientDetails(status: Int, message: String) extends ClientDetailsFailureResponse
