sequenceDiagram
    autonumber
    participant Upstream
    participant agent-client-relationships
    participant Database
    participant agent-assurance
    participant des

    Upstream->>+agent-client-relationships: POST /api/:arn/invitation
    agent-client-relationships->>Database: Read: Check for pending invitations.
    agent-client-relationships->>+agent-assurance: GET /agent-assurance/agent-details/:arn
    agent-assurance-->>-agent-client-relationships: Response
    agent-client-relationships->>+des: GET /registration/business-details/... or /vat/customer/vrn/...
    des-->>-agent-client-relationships: Response
    agent-client-relationships->>Database: Read: Check for active relationship.
    agent-client-relationships->>Database: Read: Check for partial-auth relationship (ITSA).
    agent-client-relationships->>Database: Create: Create new invitation.
    agent-client-relationships-->>-Upstream: Final Response
