sequenceDiagram
    autonumber
    participant Upstream
    participant agent-client-relationships
    participant des
    participant Database
    participant enrolment-store-proxy

    Upstream->>+agent-client-relationships: GET /client/:service/details/:clientId
    agent-client-relationships->>+des: GET /registration/individual/nino/:nino
    des-->>-agent-client-relationships: Response
    agent-client-relationships->>Database: Read: Check for any pending invitations for this client and agent.
    agent-client-relationships->>Database: Read: Check for any partial-auth invitations for this client and agent.
    agent-client-relationships->>+enrolment-store-proxy: GET /enrolment-store-proxy/enrolment-store/enrolments/:enrolmentKey/groups
    enrolment-store-proxy-->>-agent-client-relationships: Response
    agent-client-relationships-->>-Upstream: Final Response
