sequenceDiagram
    autonumber
    participant Upstream
    participant agent-client-relationships
    participant Database
    participant agent-fi-relationship

    Upstream->>+agent-client-relationships: GET /customer-status
    agent-client-relationships->>Database: Read: Find non-suspended invitations.
    agent-client-relationships->>Database: Read: Find partial-auth records by NINO.
    agent-client-relationships->>+agent-fi-relationship: GET /agent-fi-relationship/irv-active-relationship/client/:nino
    agent-fi-relationship-->>-agent-client-relationships: Response
    agent-client-relationships->>Database: Read: Check for other active relationships.
    agent-client-relationships-->>-Upstream: Final Response (CustomerStatus)
