sequenceDiagram
    autonumber
    participant Upstream
    participant agent-client-relationships
    participant des
    participant Database

    Upstream->>+agent-client-relationships: POST /agent/:arn/authorisation-request
    agent-client-relationships->>+des: GET /registration/individual/nino/:nino
    des-->>-agent-client-relationships: Response
    agent-client-relationships->>Database: Create: Create a new invitation record with a 'Pending' status.
    agent-client-relationships-->>-Upstream: Final Response
