sequenceDiagram
    autonumber
    participant Upstream
    participant agent-client-relationships
    participant Database
    participant agent-assurance

    Upstream->>+agent-client-relationships: GET /agent/agent-reference/uid/:uid/:normalizedAgentName
    agent-client-relationships->>Database: Read: Find agent reference record by UID.
    agent-client-relationships->>+agent-assurance: GET /agent-assurance/agent-details/:arn
    agent-assurance-->>-agent-client-relationships: Response
    agent-client-relationships-->>-Upstream: Final Response
