sequenceDiagram
    autonumber
    participant Upstream
    participant agent-client-relationships
    participant Database
    participant enrolment-store-proxy

    Upstream->>+agent-client-relationships: POST /client/validate-invitation
    agent-client-relationships->>Database: Read: Check for existing pending invitations for the client and service.
    agent-client-relationships->>+enrolment-store-proxy: GET /enrolment-store-proxy/enrolment-store/enrolments/:enrolmentKey/groups
    enrolment-store-proxy-->>-agent-client-relationships: Response
    agent-client-relationships-->>-Upstream: Final Response
