sequenceDiagram
    autonumber
    participant Upstream
    participant agent-client-relationships
    participant agent-fi-relationship
    participant Database
    participant enrolment-store-proxy

    Upstream->>+agent-client-relationships: POST /agent/:arn/remove-authorisation
    alt PIR Service
        agent-client-relationships->>+agent-fi-relationship: DELETE /agent-fi-relationship/relationships/agent/:arn/service/:service/client/:clientId
        agent-fi-relationship-->>-agent-client-relationships: Response
    end
    alt Alt-ITSA Service
        agent-client-relationships->>Database: Delete: Remove the partial-auth record.
    end
    agent-client-relationships->>Database: Update: Find the original invitation and mark it as relationship ended.
    alt Default Services
        agent-client-relationships->>+enrolment-store-proxy: DELETE /enrolment-store-proxy/enrolment-store/groups/:groupId/enrolments/:enrolmentKey
        enrolment-store-proxy-->>-agent-client-relationships: Response
    end
    agent-client-relationships-->>-Upstream: Final Response
