sequenceDiagram
    autonumber
    participant Upstream
    participant agent-client-relationships
    participant Database
    participant agent-assurance

    Upstream->>+agent-client-relationships: POST /stride/active-relationships
    agent-client-relationships->>Database: Read: Find all active relationships for the provided list of clients.
    agent-client-relationships->>+agent-assurance: GET /agent-assurance/agent-details/:arn
    agent-assurance-->>-agent-client-relationships: Response
    agent-client-relationships-->>-Upstream: Final Response
