sequenceDiagram
    autonumber
    participant Upstream
    participant agent-client-relationships
    participant Database
    participant citizen-details
    participant agent-assurance

    Upstream->>+agent-client-relationships: GET /stride/partial-auths/nino/:nino
    agent-client-relationships->>Database: Read: Get all partial-auth records for the given NINO.
    agent-client-relationships->>+citizen-details: GET /citizen-details/nino/:nino
    citizen-details-->>-agent-client-relationships: Response
    agent-client-relationships->>+agent-assurance: GET /agent-assurance/agent-details/:arn
    agent-assurance-->>-agent-client-relationships: Response
    agent-client-relationships-->>-Upstream: Final Response
